import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Giscus from "@giscus/react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Giscus Nextjs Integration</h1>

        <p className={styles.description}>
          Check out the full tutorial at{" "}
          <a
            href="https://www.sewb.dev"
            style={{
              color: "lightblue",
            }}
          >
            {" "}
            sewb.dev
          </a>
        </p>

        <Giscus
          repo="sewbdotdev/giscus-next-integration"
          repoId="R_kgDOHPv7gA"
          category="Announcements"
          categoryId="DIC_kwDOHPv7gM4COz-s"
          mapping="pathname"
          reactionsEnabled="1"
          emitMetadata="1"
          theme="light"
          inputPosition="top"
          loading="lazy"
          lang={"en"}

        />
      </main>
    </div>
  );
};

export default Home;
